add pages components
htmlacademy-react/2298571-six-cities-15 pull request #3
Opened 2024-02-16 21:49 UTC by Dzasikivarasi

2024-02-17 11:07 UTC, baileys-li requested changes

2024-02-17 11:07 UTC, baileys-li commented on src/components/app/app.tsx
> +type PlaceType = {
Повторный тип

2024-02-17 13:59 UTC, merged

2024-02-20 16:24 UTC, potyoma commented on src/components/card/card.tsx
> +type CardProps = {
вынеси данные, касающие именно карточки оффера в отдельный тип

2024-02-20 16:24 UTC, potyoma commented on src/data.tsx
расширение `.ts`

2024-02-20 16:24 UTC, potyoma commented on src/pages/main/main.tsx
> +export default function Main({ DATA }: { DATA: PlaceType[] }) {
`{ data = DATA }`

2024-02-20 16:24 UTC, potyoma commented on src/pages/main/main.tsx
> +  const cardsList = DATA.map((place) => (
это лучше сделать функцией вне объявления компонента или отдельным компонентом